================================================================================
# ANEXO                                
USANDO df_pp_ventas5f y df_producto5

## PROBABLES MEJORAS A FUTURO        version 31 / 4-nov 21:34


### *Trabajo en curso*

1 Crear lista categorias = df_ventas_final["categoria"].unique()  

2 Crear tabla df_producto con id_producto, producto, id_categoria, categoria

Se observó que:
1. Las ventas contienen productos con la misma denominación, sin ninguna id como para identificarlos. Pertenecen a distintas ventas individuales y tienen distinto precio.

2. Por tal razón es dificil hacer una evaluación seria del resultado de la campaña publicitaria, porque corresponde a distintos productos agrupados, con precio sin adjudicar.

3. La campaña de marketing posee el costo publicitario por producto (generico/agregado) pero no hay como relacionarlo con el costo_unitario, ni con el precio_venta

4. Sacar un precio_promedio, no estoy seguro que sirva mucho, porque la venta podria haberse hecho a un valor menor que el precio_unitario_promedio, debido a la gran dispersión de precios

Hemos visto que para el producto "Adorno de pared", los precios estan distribuidos en 3 segmentos o rangos, la idea es hacer un promedio por rango y
luego renombrar los productos segun el rango, por ej:
"Adorno de pared" => "Adorno de pared R1"

De esta manera en lugar de tener 100 productos genericos los tendriamos divididos por rango de precios y con un nuevo nombre_producto y un nuevo id_producto que los represente
  
.  

ESTE ES EL ENFOQUE QUE VOY ATRATAR DE DESARROLLAR

.  

## Por este motivo el DF df_producto, y df_pp_ventas van a ir evolucionando....  
.

In [ ]:
import pandas as pd

# Import dataset ventas final
url = "https://raw.githubusercontent.com/alex-degarate/TT-2C2025-Data-Analitycs-Notebooks/main/PreEntrega/Datasets/"

#df_ventas_final = pd.read_csv( url + "ventas_final.csv")

In [ ]:
# Import dataset clientes
#df_clientes_final = pd.read_csv( url + "clientes_final.csv")

In [ ]:
# Import dataset marketing
df_marketing_final = pd.read_csv( url + "marketing_final.csv")

In [ ]:
df_marketing_final.info()

## a partir de ahora vamos a trabajar con df_pp_ventas2 / 4 (desde disco)

In [1]:
import pandas as pd

In [21]:
# habilito mostrar hasta 100 filas por DF
pd.set_option('display.max_rows', 100)

### archivos para probar puntos finales

In [2]:
# a partir de ahora vamos a trabajar con df_pp_ventas2 /4
url2 ="https://raw.githubusercontent.com/alex-degarate/DAnalytics/main/preproyecto/Datasets/tempo/"
df_pp_ventas = pd.read_csv( url2 + "df_pp_ventas5f.csv",index_col=0 )

In [84]:
# @title
#df_pp_ventas['producto'] = df_pp_ventas['producto'].replace('Adorno de pared-R1', 'Adorno de pared')
#df_pp_ventas['producto'] = df_pp_ventas['producto'].replace('Adorno de pared-R2', 'Adorno de pared')
#df_pp_ventas['producto'] = df_pp_ventas['producto'].replace('Adorno de pared-R3', 'Adorno de pared')

# Display the updated DataFrame to confirm the changes
#df_pp_ventas[df_pp_ventas["producto"] == 'Adorno de pared'].head(100)

# agrego campo / columna ['precio_rango']
# df_pp_ventas['precio_rango'] = ""

In [ ]:
# @title
## Hacemos una copia para hacer pruebas o si la IA lo arruina
df_pp_ventas2 = df_pp_ventas.copy()
df_pp_ventas2.info()

In [96]:
df_pp_ventas2.head(5)

,id_venta,id_producto,producto,precio_unit,cantidad,fecha_venta,categoria,rango,precio_rango
0,792,192,Cuadro decorativo,69.94,5,2024-01-02,Decoración,R2,0.0
1,811,0,Lámpara de mesa,105.10,5,2024-01-02,Decoración,NaN,0.0
2,1156,0,Secadora,97.96,3,2024-01-02,Electrodomésticos,NaN,0.0
3,1372,0,Heladera,114.35,8,2024-01-02,Electrodomésticos,NaN,0.0
4,1546,0,Secadora,106.21,4,2024-01-02,Electrodomésticos,NaN,0.0

## Lista alfabetica de productos

In [52]:
# @title

lista_productos = ["Adorno de pared","Alfombra","Aspiradora","Auriculares","Batidora","Cafetera","Candelabro",
"Consola de videojuegos","Cortinas","Cuadro decorativo","Cámara digital","Elementos de cerámica","Espejo decorativo","Freidora eléctrica","Heladera",
"Horno eléctrico","Jarrón decorativo","Laptop","Lavadora","Lámpara de mesa","Microondas","Parlantes Bluetooth","Plancha de vapor ","Proyector","Rincón de plantas","Secadora","SmartWatch","Smartphone","Tablet","Televisor"]

# Creamos una lista de listas, agregando el segundo elemento vacío, para llevar
# control de lo procesado

# agregue un 3er campo   count de cada producto
#                          |
aLista_prod = [[nombre, 0] for nombre in lista_productos]

.  

===== AGREGO EL CONTADOR PARA CADA PRODUCTO, a df_aLista_prod

In [126]:

# Convert the list of lists to a DataFrame
df_aLista_prod = pd.DataFrame(aLista_prod, columns=['Producto', 'Procesado'])

# obtengo el contador para cada producto en df_pp_ventas2
columna3 = df_pp_ventas2["producto"].value_counts().sort_index()

df_columna3 = columna3.reset_index()
# elimino la columna producto, me quedo solo con ["count"]
df_columna3 = df_columna3.drop(columns=['producto'])

#display(df_columna3)
# agrego al df_aLista_prod una nueva columna/Serie ["Count"]
df_aLista_prod['Count'] = df_columna3['count']

display(df_aLista_prod)

# ESTE DF deberia cargarlo como archivo externo y eliminar los pasos anteriores

                  Producto  Procesado  Count
0          Adorno de pared          0    100
1                 Alfombra          0    100
2               Aspiradora          0    100
3              Auriculares          0    143
4                 Batidora          0    100
5                 Cafetera          0    117
6               Candelabro          0     24
7   Consola de videojuegos          0     99
8                 Cortinas          0    100
9        Cuadro decorativo          0    100
10          Cámara digital          0    100
11   Elementos de cerámica          0     99
12       Espejo decorativo          0    100
13      Freidora eléctrica          0    100
14                Heladera          0     48
15         Horno eléctrico          0    100
16       Jarrón decorativo          0    100
17                  Laptop          0    100
18                Lavadora          0    100
19         Lámpara de mesa          0    176
20              Microondas          0    135
21     Parlantes Bluetooth          0     98
22       Plancha de vapor           0    100
23               Proyector          0     99
24       Rincón de plantas          0    101
25                Secadora          0    100
26              SmartWatch          0    100
27              Smartphone          0    101
28                  Tablet          0     58
29               Televisor          0    100

# Utilizaremos el que esta en curso df_producto5
Para hacer de enlace como clave primaria entre ventas y marketing

In [ ]:
# @title
# ventas_categoria.sort_values(by="valor_venta", ascending=False, inplace=True)
# mal df_pp_ventas[df_pp_ventas["producto"]].sum()

# IMPRIMIR la lista de productos ordenados alfabeticamente y las ventas
#----------------------------------------------------
# df_pp_ventas["producto"].value_counts().sort_index()
#---------------------------------------------------

## El DF df_producto5 es el que esta actualizado y el que debe cargarse desde github

In [57]:
url2 ="https://raw.githubusercontent.com/alex-degarate/DAnalytics/main/preproyecto/Datasets/tempo/"

# OJO ! se levanta como df_producto
# df_producto = pd.read_csv( url2 + "df_producto5.csv", index_col=0 )
df_producto = pd.read_csv( url2 + "df_producto5.csv", index_col=0 )
df_producto.info()

<class 'pandas.core.frame.DataFrame'>
Index: 90 entries, 0 to 89
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_producto   90 non-null     int64
 1   producto      90 non-null     object
 2   id_categoria  90 non-null     int64
 3   categoria     90 non-null     object
 4   rango         90 non-null     object
 5   media_rango   90 non-null     float64
 6   precio_rango  9 non-null      object
 7   prod_gener    90 non-null     object
dtypes: float64(1), int64(2), object(5)
memory usage: 6.3+ KB

In [ ]:
# los unicos datos de precio_rango son donde se procesan las medias y rangos ? VER

display(df_producto[['id_producto', 'producto', 'rango','media_rango', 'precio_rango']].head(90))

### Aparecieron imprevistos que complican el codigo, y tengo que reintroducir el nombre generico del producto, independiente del rango a que pertenezca.   

### Aparecieron datos faltantes y NO SE POR QUE !!!  

### Voy a reiniciar el codigo desde Adorno de pared en adelante...

## REVISAR la info que no haya datos vacios / nan etc

### Tampoco debo de olvidarme de actualizar y guardar df_producto y df_pp_ventas
## **Deben ir juntos y sincronizados !!!**

In [129]:
#df_producto['prod_gener'] = df_producto['producto'].str.replace('-R[123]', '', regex=True)
# la linea de arriba ya fue procesada y guardada al archivo actual en disco
display(df_producto[df_producto["prod_gener"] == "Aspiradora"].head())

,id_producto,producto,id_categoria,categoria,rango,media_rango,precio_rango,prod_gener
6,121,Aspiradora-R1,2,Electrodomésticos,R1,0.0,NaN,Aspiradora
7,122,Aspiradora-R2,2,Electrodomésticos,R2,0.0,NaN,Aspiradora
8,123,Aspiradora-R3,2,Electrodomésticos,R3,0.0,NaN,Aspiradora

### guardamos df_producto como producto5.csv para su uso posterior

In [ ]:
# @title
# guardamos df_producto para su uso posterior, incrementar el digito al guardar

def guardar_df_a_csv(df, nombre_archivo):
    df.to_csv(nombre_archivo, index=True)
    print(f"DataFrame guardado como {nombre_archivo}")

# Llamada a la función para guardar df_
# guardar_df_a_csv( df_producto4, 'df_producto5.csv')

# df_producto.to_csv('df_producto5.csv', index=True)

# df_pp_ventas.to_csv('df_pp_ventas4.csv', index=True)

completar los [precio_rango] que faltan

In [ ]:
# @title


df_pp_ventas2[ df_pp_ventas2["producto"] == "Auriculares"].head(5)

# LO QUE FALTABA

In [ ]:
# @title
df_producto[df_producto["prod_gener"] == "Auriculares"]

In [ ]:
# @title
# LO QUE FALTABA


#df_pp_ventas2.iat[2475, 1] = 111
#df_pp_ventas2.iloc[2475, 7] = 'R1'
#df_pp_ventas2.iloc[2475, 8] = "28-54"
#display( df_pp_ventas2.iloc[2475])

## asignar [precio_rango] a los productos ya procesados que no fueron updated

In [ ]:
# @title

df_pp_ventas2.loc[df_pp_ventas2['id_producto'] == 131, 'precio_rango'] = '28-54'
df_pp_ventas2.loc[df_pp_ventas2['id_producto'] == 132, 'precio_rango'] = '54-89'
df_pp_ventas2.loc[df_pp_ventas2['id_producto'] == 133, 'precio_rango'] = '89-125'

# Display the updated rows to verify the change
df_pp_ventas2[ df_pp_ventas2["producto"] == "Aspiradora"].head(100)

================================================================================

.

# PASOS PARA AUTOMATIZAR
## PARA TODOS LOS PRODUCTOS

### 1. Recorrer La lista de productos,
&emsp; si el 2do campo esta en cero significa que no fue procesado, 1=completo
lista_productos = [["Adorno de pared", 1]

### 2. OBTENER NOMBRE DEL PRODUCTO A PROCESAR

### 3. CREAR EL DF TEMPORAL

### 4. VISUALIZAR ESTADISTICA CON DESCRIBE

### 5 CALCULAR RANGOS, MEDIA

### 6. CALCULAR Cuartiles (0.33 y 0.66)

### 7. GRAFICAR HISTOGRAMA

### 8. REEMPLAZAR DATOS EN DF TEMPORAL

### 9. ACTUALIZAR df_pp_ventas

## 2. OBTENER NOMBRE DEL PRODUCTO A PROCESAR

In [323]:

nLenght = df_aLista_prod.shape[0]
print(f"{nLenght}")

df_aLista_prod.iat[0, 1] = 1  # Adorno de pared
df_aLista_prod.iat[1, 1] = 1  # Alfombra
df_aLista_prod.iat[2, 1] = 1  # Aspiradora
df_aLista_prod.iat[3, 1] = 1  # Auriculares
df_aLista_prod.iat[4, 1] = 1  # Batidora
df_aLista_prod.iat[5, 1] = 1  # Cafetera
df_aLista_prod.iat[6, 1] = 1  # Candelabro
df_aLista_prod.iat[7, 1] = 1  # Consola de videojuegos

df_aLista_prod.iat[9, 1] = 1  # Cuadro decorativo

for i in range( nLenght):

    if df_aLista_prod.iat[i, 1] == 0:
       prod_actual = df_aLista_prod.iat[i, 0]      # nombre producto
       print(f"{prod_actual}")
       break

print(f"El primer registro a procesar es {[i]}: {prod_actual}")

30
Cortinas
El primer registro a procesar es [8]: Cortinas

# Producto ACTUAL

In [299]:
print( f"df_{prod_actual} \n")
print( df_pp_ventas2[ df_pp_ventas2["producto"] == prod_actual].count())

df_Consola de videojuegos

id_venta        99
id_producto     99
producto        99
precio_unit     99
cantidad        99
fecha_venta     99
categoria       99
rango            0
precio_rango    99
dtype: int64

In [300]:
# df_pp_ventas2 = df_pp_ventas.sort_values(by="producto", ascending=True)
df_pp_ventas2[df_pp_ventas2["producto"] == prod_actual].head(100)

,id_venta,id_producto,producto,precio_unit,cantidad,fecha_venta,categoria,rango,precio_rango
32,2180,0,Consola de videojuegos,102.57,9,2024-01-06,Electrónica,NaN,0.0
48,2920,0,Consola de videojuegos,29.49,2,2024-01-07,Electrónica,NaN,0.0
92,2980,0,Consola de videojuegos,110.60,12,2024-01-12,Electrónica,NaN,0.0
117,2590,0,Consola de videojuegos,99.14,6,2024-01-15,Electrónica,NaN,0.0
129,2220,0,Consola de videojuegos,31.57,1,2024-01-16,Electrónica,NaN,0.0
178,2560,0,Consola de videojuegos,87.23,5,2024-01-21,Electrónica,NaN,0.0
190,2690,0,Consola de videojuegos,102.40,2,2024-01-23,Electrónica,NaN,0.0
208,2340,0,Consola de videojuegos,109.68,5,2024-01-25,Electrónica,NaN,0.0
241,2240,0,Consola de videojuegos,43.35,8,2024-01-29,Electrónica,NaN,0.0
244,2870,0,Consola de videojuegos,72.39,1,2024-01-29,Electrónica,NaN,0.0
275,2680,0,Consola de videojuegos,89.96,2,2024-02-01,Electrónica,NaN,0.0
362,2440,0,Consola de videojuegos,110.79,8,2024-02-11,Electrónica,NaN,0.0
431,2900,0,Consola de videojuegos,63.26,2,2024-02-20,Electrónica,NaN,0.0
494,2810,0,Consola de videojuegos,31.09,1,2024-02-27,Electrónica,NaN,0.0
505,2110,0,Consola de videojuegos,81.69,4,2024-02-28,Electrónica,NaN,0.0
562,2270,0,Consola de videojuegos,117.47,8,2024-03-07,Electrónica,NaN,0.0
563,2550,0,Consola de videojuegos,118.87,6,2024-03-07,Electrónica,NaN,0.0
642,2170,0,Consola de videojuegos,122.40,1,2024-03-15,Electrónica,NaN,0.0
646,2950,0,Consola de videojuegos,29.14,10,2024-03-15,Electrónica,NaN,0.0
654,2030,0,Consola de videojuegos,108.00,9,2024-03-16,Electrónica,NaN,0.0
695,2530,0,Consola de videojuegos,54.04,8,2024-03-20,Electrónica,NaN,0.0
702,2200,0,Consola de videojuegos,44.36,10,2024-03-21,Electrónica,NaN,0.0
703,2650,0,Consola de videojuegos,50.77,10,2024-03-21,Electrónica,NaN,0.0
713,2100,0,Consola de videojuegos,94.73,1,2024-03-22,Electrónica,NaN,0.0
727,2420,0,Consola de videojuegos,72.78,9,2024-03-24,Electrónica,NaN,0.0
729,2480,0,Consola de videojuegos,96.21,11,2024-03-24,Electrónica,NaN,0.0
757,2830,0,Consola de videojuegos,123.72,3,2024-03-28,Electrónica,NaN,0.0
784,2310,0,Consola de videojuegos,102.41,5,2024-04-01,Electrónica,NaN,0.0
833,2080,0,Consola de videojuegos,100.69,7,2024-04-06,Electrónica,NaN,0.0
877,2370,0,Consola de videojuegos,46.08,7,2024-04-11,Electrónica,NaN,0.0
893,2490,0,Consola de videojuegos,122.79,6,2024-04-13,Electrónica,NaN,0.0
928,2610,0,Consola de videojuegos,49.74,9,2024-04-16,Electrónica,NaN,0.0
1014,2580,0,Consola de videojuegos,107.55,7,2024-04-26,Electrónica,NaN,0.0
1075,2510,0,Consola de videojuegos,70.04,12,2024-05-02,Electrónica,NaN,0.0
1114,2780,0,Consola de videojuegos,65.35,6,2024-05-06,Electrónica,NaN,0.0
1139,2840,0,Consola de videojuegos,69.43,3,2024-05-09,Electrónica,NaN,0.0
1161,2860,0,Consola de videojuegos,100.61,6,2024-05-12,Electrónica,NaN,0.0
1210,2999,0,Consola de videojuegos,52.08,4,2024-05-17,Electrónica,NaN,0.0
1247,2150,0,Consola de videojuegos,66.93,5,2024-05-21,Electrónica,NaN,0.0
1379,2040,0,Consola de videojuegos,43.95,11,2024-06-06,Electrónica,NaN,0.0
1386,2750,0,Consola de videojuegos,38.97,9,2024-06-07,Electrónica,NaN,0.0
1433,2740,0,Consola de videojuegos,88.36,5,2024-06-13,Electrónica,NaN,0.0
1469,2120,0,Consola de videojuegos,99.63,6,2024-06-19,Electrónica,NaN,0.0
1480,2290,0,Consola de videojuegos,115.96,7,2024-06-21,Electrónica,NaN,0.0
1518,2700,0,Consola de videojuegos,39.68,12,2024-06-26,Electrónica,NaN,0.0
1530,2730,0,Consola de videojuegos,87.79,2,2024-06-28,Electrónica,NaN,0.0
1575,2770,0,Consola de videojuegos,60.92,8,2024-07-03,Electrónica,NaN,0.0
1606,2910,0,Consola de videojuegos,122.48,7,2024-07-07,Electrónica,NaN,0.0
1675,2280,0,Consola de videojuegos,108.67,3,2024-07-16,Electrónica,NaN,0.0
1683,2570,0,Consola de videojuegos,122.81,6,2024-07-17,Electrónica,NaN,0.0
1695,2350,0,Consola de videojuegos,90.18,4,2024-07-19,Electrónica,NaN,0.0
1737,2070,0,Consola de videojuegos,39.85,6,2024-07-24,Electrónica,NaN,0.0
1751,2390,0,Consola de videojuegos,108.30,4,2024-07-26,Electrónica,NaN,0.0
1791,2130,0,Consola de videojuegos,41.12,6,2024-07-31,Electrónica,NaN,0.0
1802,2050,0,Consola de videojuegos,88.73,12,2024-08-01,Electrónica,NaN,0.0
1815,2880,0,Consola de videojuegos,79.76,12,2024-08-02,Electrónica,NaN,0.0
1838,2620,0,Consola de videojuegos,51.74,7,2024-08-04,Electrónica,NaN,0.0
1840,2800,0,Consola de videojuegos,121.62,2,2024-08-04,Electrónica,NaN,0.0
1846,2790,0,Consola de videojuegos,83.70,1,2024-08-05,Electrónica,NaN,0.0
1904,2260,0,Consola de videojuegos,88.37,4,2024-08-14,Electrónica,NaN,0.0
1930,2540,0,Consola de videojuegos,77.43,6,2024-08-18,Electrónica,NaN,0.0
1958,2160,0,Consola de videojuegos,92.56,3,2024-08-21,Electrónica,NaN,0.0
2003,2300,0,Consola de videojuegos,51.18,8,2024-08-26,Electrónica,NaN,0.0
2021,2460,0,Consola de videojuegos,31.43,12,2024-08-28,Electrónica,NaN,0.0
2061,2630,0,Consola de videojuegos,79.88,1,2024-09-02,Electrónica,NaN,0.0
2071,2760,0,Consola de videojuegos,78.13,7,2024-09-04,Electrónica,NaN,0.0
2107,2360,0,Consola de videojuegos,43.59,7,2024-09-08,Electrónica,NaN,0.0
2141,2720,0,Consola de videojuegos,73.08,7,2024-09-12,Electrónica,NaN,0.0
2201,2330,0,Consola de videojuegos,122.43,4,2024-09-19,Electrónica,NaN,0.0
2209,2430,0,Consola de videojuegos,62.77,7,2024-09-21,Electrónica,NaN,0.0
2239,2500,0,Consola de videojuegos,53.64,8,2024-09-25,Electrónica,NaN,0.0
2244,2400,0,Consola de videojuegos,84.09,12,2024-09-26,Electrónica,NaN,0.0
2253,2190,0,Consola de videojuegos,48.86,3,2024-09-27,Electrónica,NaN,0.0
2260,2820,0,Consola de videojuegos,32.49,6,2024-09-28,Electrónica,NaN,0.0
2270,2450,0,Consola de videojuegos,87.91,4,2024-09-29,Electrónica,NaN,0.0
2272,2600,0,Consola de videojuegos,94.57,3,2024-09-29,Electrónica,NaN,0.0
2384,2470,0,Consola de videojuegos,111.81,9,2024-10-12,Electrónica,NaN,0.0
2389,2710,0,Consola de videojuegos,41.81,7,2024-10-13,Electrónica,NaN,0.0
2401,2960,0,Consola de videojuegos,87.02,11,2024-10-15,Electrónica,NaN,0.0
2439,2940,0,Consola de videojuegos,34.04,6,2024-10-22,Electrónica,NaN,0.0
2500,2660,0,Consola de videojuegos,124.46,4,2024-10-29,Electrónica,NaN,0.0
2519,2890,0,Consola de videojuegos,105.99,5,2024-10-31,Electrónica,NaN,0.0
2562,2250,0,Consola de videojuegos,78.68,11,2024-11-07,Electrónica,NaN,0.0
2581,2850,0,Consola de videojuegos,84.81,4,2024-11-09,Electrónica,NaN,0.0
2588,2010,0,Consola de videojuegos,51.13,2,2024-11-10,Electrónica,NaN,0.0
2598,2060,0,Consola de videojuegos,73.40,5,2024-11-11,Electrónica,NaN,0.0
2694,2410,0,Consola de videojuegos,55.53,10,2024-11-23,Electrónica,NaN,0.0
2696,2670,0,Consola de videojuegos,42.62,3,2024-11-23,Electrónica,NaN,0.0
2704,2970,0,Consola de videojuegos,49.88,5,2024-11-24,Electrónica,NaN,0.0
2759,2640,0,Consola de videojuegos,40.84,9,2024-11-30,Electrónica,NaN,0.0
2781,2140,0,Consola de videojuegos,91.09,7,2024-12-02,Electrónica,NaN,0.0
2801,2090,0,Consola de videojuegos,45.15,9,2024-12-05,Electrónica,NaN,0.0
2815,2210,0,Consola de videojuegos,39.67,11,2024-12-07,Electrónica,NaN,0.0
2832,2020,0,Consola de videojuegos,30.73,6,2024-12-10,Electrónica,NaN,0.0
2862,2380,0,Consola de videojuegos,68.20,2,2024-12-14,Electrónica,NaN,0.0
2877,2520,0,Consola de videojuegos,99.63,10,2024-12-15,Electrónica,NaN,0.0
2916,2230,0,Consola de videojuegos,74.41,10,2024-12-20,Electrónica,NaN,0.0
2922,2320,0,Consola de videojuegos,83.94,8,2024-12-21,Electrónica,NaN,0.0
2997,2930,0,Consola de videojuegos,55.47,6,2024-12-30,Electrónica,NaN,0.0

# df_pp_ventas2

In [74]:
# @title
## ARREGLAR ALFOMBRA 2475 QUE LE FALTA EL ID_PRODUCTO Y RANGO

# completar datos iat[row, col] base cero
# df_pp_ventas2.iat[2475, 1] = 111
# display( df_pp_ventas2.loc[2475])
#display( df_pp_ventas2.iat[2475, 3])

## 3. CREAR EL DF TEMPORAL
### df_actual corresponde a df_xxxx.....
la idea es generalizarlo para el procesamiento de los otros productos

In [301]:
# Generamos una tabla aislada para el producto actual => xxxx

# df_actual corresponde a
df_actual = df_pp_ventas2[df_pp_ventas2["producto"] == prod_actual].copy()

media = df_actual["precio_unit"].mean()
print(f"El precio promedio para '{prod_actual}' es: {media:.2f} \n")

df_actual.describe()

El precio promedio para 'Consola de videojuegos' es: 76.35

          id_venta  id_producto  precio_unit   cantidad
count    99.000000         99.0    99.000000  99.000000
mean   2500.090909          0.0    76.346869   6.292929
std     287.386183          0.0    28.722411   3.179181
min    2010.000000          0.0    29.140000   1.000000
25%    2255.000000          0.0    50.325000   4.000000
50%    2500.000000          0.0    78.680000   6.000000
75%    2745.000000          0.0   100.120000   9.000000
max    2999.000000          0.0   124.460000  12.000000

In [302]:
df_actual.info()

<class 'pandas.core.frame.DataFrame'>
Index: 99 entries, 32 to 2997
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_venta      99 non-null     int64
 1   id_producto   99 non-null     int64
 2   producto      99 non-null     object
 3   precio_unit   99 non-null     float64
 4   cantidad      99 non-null     int64
 5   fecha_venta   99 non-null     object
 6   categoria     99 non-null     object
 7   rango         0 non-null      object
 8   precio_rango  99 non-null     object
dtypes: float64(1), int64(3), object(5)
memory usage: 7.7+ KB

### Completar en df_actual la columna ["rango"]

### 4. VISUALIZAR ESTADISTICA CON DESCRIBE

### Obtenemos info relevante mediante describe()

### 5 CALCULAR RANGOS, MEDIA

In [281]:

# Como accedo a los distintos datos de df_xxx.describe(),
# como ser min, max, etc
'''
The .describe() method in pandas returns a new DataFrame containing the
descriptive statistics.
You can access the individual statistics (like min, max, mean, etc.) from this
DataFrame using standard indexing.
'''
# Obtenemos la salida describe del DataFrame
#-------------------------------------------
def obtener_descripcion_DF(df):
    return df.describe()

df_desc = obtener_descripcion_DF( df_actual["precio_unit"])

#cuadro_decorativo_description = df_cuadro_decorativo["precio_unit"].describe()

# Accedemos a valores especificos
min_precio = int( round( df_desc['min'])) -1
max_precio = int( round( df_desc['max'])) + 1
mean_precio = df_desc['mean']

print(f"{prod_actual} \n")
print(f"PUnit Minimo: {min_precio}")
print(f"PUnit Maximo: {max_precio}")
print(f"PUnit Medio : {mean_precio:.2f} \n")

display (df_desc)

Candelabro

PUnit Minimo: 29
PUnit Maximo: 126
PUnit Medio : 74.60

count     24.000000
mean      74.595417
std       29.723373
min       29.770000
25%       50.062500
50%       72.740000
75%      104.382500
max      124.780000
Name: precio_unit, dtype: float64

In [303]:
if (max_precio / min_precio) > 2:
  print(f'En {prod_actual} => HAY DISPERSION de precios !!!')
else:
  print(f'En {prod_actual} No hay dispersion de precios')

En Consola de videojuegos => HAY DISPERSION de precios !!!


### 6. CALCULAR Cuartiles (0.33 y 0.66)

In [304]:


# Calculamos percentilo 33 de 'precio_unit'
q33_data = df_actual["precio_unit"].quantile(0.33)

# Calculamos el percentilo 66 de 'precio_unit'
q66_data = df_actual["precio_unit"].quantile(0.66)

print(f"El percentilo 33 del precio_unit para '{prod_actual}' es: {q33_data:.2f}")
print(f"El percentilo 66 del precio_unit para '{prod_actual}' es: {q66_data:.2f}")

El percentilo 33 del precio_unit para 'Consola de videojuegos' es: 55.49
El percentilo 66 del precio_unit para 'Consola de videojuegos' es: 90.11

### 7. GRAFICAR HISTOGRAMA

In [ ]:
'''
# @title
# Agregamos un plot para visualizar graficamente la distribución
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

sns.histplot( df_actual["precio_unit"], bins=100, kde=True, edgecolor="black")
plt.title("Distribución de precio_unit - "+ prod_actual)
plt.xlabel("Precio Unitario ($)")
plt.ylabel("Frecuencia")

# Seteamos x-axis ticks a intervalo s de 10
plt.xticks(np.arange(0, df_actual ["precio_unit"].max() + 10, 10))

plt.show()
'''


###  CALCULAR RANGOS
Aca calculamos los puntos de corte y los asignamos a df_actual["precio_rango"]

In [306]:
# Definimos los bins (puntos de corte)
r1_linf = min_precio
r1_lsup = int( round( q33_data))
r2_linf = r1_lsup
r2_lsup = int( round( q66_data))
r3_linf = r2_lsup
r3_lsup = max_precio

#print(f"{r2_lsup} \n")

#bins = [26, 61, 87, 130]
bins = [r1_linf, r1_lsup, r3_linf, r3_lsup]
print( bins)
print("\n")

# Definimos las etiquetas para los rangos
# labels = ['26-61', '61-86', '86-125']
rg1 = f"{r1_linf}-{r1_lsup}"
rg2 = f"{r2_linf}-{r2_lsup}"
rg3 = f"{r3_linf}-{r3_lsup}"
labels = [ rg1, rg2, rg3 ]


# Creamos una nueva columna 'precio_rango' para estratificar 'precio_unit' dentro de los cut-off
df_actual['precio_rango'] = pd.cut( df_actual['precio_unit'], bins=bins, labels=labels, right=False)

# Mostramos la cantidad de items precios en cada rango de precios
display( df_actual['precio_rango'].value_counts())

# Display the first few rows with the new column
print("\n===================== DF_ACTUAL =====================\n")
display( df_actual.head(10))

[29, 55, 90, 126]

precio_rango
90-126    34
55-90     33
29-55     32
Name: count, dtype: int64

===================== DF_ACTUAL =====================

,id_venta,id_producto,producto,precio_unit,cantidad,fecha_venta,categoria,rango,precio_rango
32,2180,0,Consola de videojuegos,102.57,9,2024-01-06,Electrónica,NaN,90-126
48,2920,0,Consola de videojuegos,29.49,2,2024-01-07,Electrónica,NaN,29-55
92,2980,0,Consola de videojuegos,110.60,12,2024-01-12,Electrónica,NaN,90-126
117,2590,0,Consola de videojuegos,99.14,6,2024-01-15,Electrónica,NaN,90-126
129,2220,0,Consola de videojuegos,31.57,1,2024-01-16,Electrónica,NaN,29-55
178,2560,0,Consola de videojuegos,87.23,5,2024-01-21,Electrónica,NaN,55-90
190,2690,0,Consola de videojuegos,102.40,2,2024-01-23,Electrónica,NaN,90-126
208,2340,0,Consola de videojuegos,109.68,5,2024-01-25,Electrónica,NaN,90-126
241,2240,0,Consola de videojuegos,43.35,8,2024-01-29,Electrónica,NaN,29-55
244,2870,0,Consola de videojuegos,72.39,1,2024-01-29,Electrónica,NaN,55-90



# OJO !!!
## observo que el precio_rango NO aparece en df_pp_ventas2 y SI en df_actual
ACCION a TOMAR ???

In [ ]:
# @title
df_actual.info()

.

## CALCULAMOS LA MEDIA PARA CADA RANGO: R1, R2, R3 DEL PRODUCTO

In [308]:
# Yo RENOMBRE la desc producto, pero tal vez seria mejor agregar un
# campo con la clasif x RANGO => LO ESTOY RECONSIDERANDO

# Observamos que hay 3 rangos de datos para xxxxx
# Calculamos esos rangos aproxim dividiendolos en terciles

# estos limites son enteros

# Cambie este array para usarlo en una funcion
# limite   suma cant  Med
rango1 = [  0,   0,  0.0 ]
rango2 = [  0,   0,  0.0 ]
rango3 = [  0,   0,  0.0 ]

# Recorre df_actual  la tabla sacada de df_pp_ventas, para producto "xxxx"

nLenght = df_actual.shape[0]
print(f"{nLenght}")

#        df_cuadro_decorativo.iat[ num_fila, num_col ]  con indice= 0
# print( df_cuadro_decorativo.iat[0, 2])

# Recorremos la tabla viendo el PU en que rango cae y lo clasificamos
# el valor lo guardamos en rango y lo agregamos al campo precio_rango

for i in range( nLenght):

    pu = df_actual.iat[i, 3]      # Precio Unitario

    nomP = df_actual.iat[i, 2]    # nombre producto

    if pu > r1_linf and pu <= r1_lsup:
        rango1[0] += pu        # suma pu
        rango1[1] += 1         # count
        #df_actual.iat[i, 2] = nomP #+ "-R1"
        df_actual.iat[i, 7] = "R1"    # actualizo rango del producto

    elif pu > r2_linf and pu <= r2_lsup:
        rango2[0] += pu        # suma pu
        rango2[1] += 1         # count
        #df_actual.iat[i, 2] = nomP #+ "-R2"
        df_actual.iat[i, 7] = "R2"

    elif pu > r3_linf and pu <= r3_lsup:
        rango3[0] += pu        # suma pu
        rango3[1] += 1         # count
        #df_actual.iat[i, 2] = nomP #+ "-R3"
        df_actual.iat[i, 7] = "R3"


if df_actual.iat[i, 0] == 0:
   display( f"{i} {df_actual.iat[i, 1]} ERROR \n")

99

In [ ]:
display(df_actual.iloc[45])

## Las medias_rango y precio_rango se deben copiar en [df_producto]

In [309]:
# Calculamos las medias x rango
# rango1[0] = suma pu, rango1[1] = contador
media_rango1 = round( rango1[0]/rango1[1], 2)
media_rango2 = round( rango2[0]/rango2[1], 2)
media_rango3 = round( rango3[0]/rango3[1], 2)

#Visualizamos las medias
print(f"media_rango1 : {media_rango1}")
print(f"media_rango2 : {media_rango2}")
print(f"media_rango3 : {media_rango3}")

# En las celdas de mas abajo lo graficamos

media_rango1 : 42.32
media_rango2 : 76.41
media_rango3 : 108.32

In [ ]:
# habilito mostrar hasta 100 filas por DF
pd.set_option('display.max_rows', 100)

In [310]:
# Copiar desde df_producto id_producto a df_pp_ventas para articulo xxxx
tabla_codigos = df_producto[df_producto["producto"].str.contains( prod_actual, na=False)][["id_producto", "producto", "rango", "prod_gener"]].copy()

display(tabla_codigos)

    id_producto                   producto rango              prod_gener
21          171  Consola de videojuegos-R1    R1  Consola de videojuegos
22          172  Consola de videojuegos-R2    R2  Consola de videojuegos
23          173  Consola de videojuegos-R3    R3  Consola de videojuegos

## En DF_PRODUCTO Guardamos las media_rango y precio_rango

In [311]:
# Obtiene el index de la primera fila en tabla_codigos que corresponde a los
# registos del df_producto para actualizar media_rango y media_precio
recno1 = tabla_codigos.index[0]
recno2 = tabla_codigos.index[1]
recno3 = tabla_codigos.index[2]
print( recno1, recno2, recno3)

#print(f"el index de la primera fila para + '{prod_actual}' en df_producto es: {recno1}"

# Guardamos las media_rango
df_producto.iat[recno1, 5] = media_rango1
df_producto.iat[recno2, 5] = media_rango2
df_producto.iat[recno3, 5] = media_rango3

# Guardamos las precio_rango
df_producto.iat[recno1, 6] = rg1
df_producto.iat[recno2, 6] = rg2
df_producto.iat[recno3, 6] = rg3
#print( df_producto.iat[recno3, 6])

# If you want all indices, you can simply access the index attribute
all_indices = tabla_codigos.index
#print(f"All indices for '{prod_actual}' in df_producto are: {list(all_indices)}")

21 22 23

In [312]:
display(df_producto.loc[all_indices])

,id_producto,producto,id_categoria,categoria,rango,media_rango,precio_rango,prod_gener
21,171,Consola de videojuegos-R1,3,Electrónica,R1,42.32,29-55,Consola de videojuegos
22,172,Consola de videojuegos-R2,3,Electrónica,R2,76.41,55-90,Consola de videojuegos
23,173,Consola de videojuegos-R3,3,Electrónica,R3,108.32,90-126,Consola de videojuegos

##

### Recorro df_actual completando los datos:  [id_producto]

In [313]:

# OJO ACA si esta habilitado el unnamed index !!! no va a coincidir
articulo = tabla_codigos.iat[0, 3] # nombre producto
cod1 = tabla_codigos.iat[0, 0] # id_producto
cod2 = tabla_codigos.iat[1, 0]
cod3 = tabla_codigos.iat[2, 0]

nLenght2 = len( df_actual )
#print(f"{nLenght2}")
print(f"producto: {articulo}")
#print(f"code0 {cod1}")  # id_producto
#print(f"code1 {cod2}")
#print(f"code2 {cod3}")
#print(f"code1 {tabla_codigos.iat[0, 1]}")  # nombre producto
#print(f"code2 {tabla_codigos.iat[0, 2]}")  # rango R1, R2,R3
#print(f"code3 {tabla_codigos.iat[0, 3]}")  # prod_gener

for i in range( nLenght2):

    if df_actual.iat[i, 2] == articulo:  # nombre producto

       if df_actual.iat[i, 7] == "R1":
          df_actual.iat[i, 1] = cod1

       elif df_actual.iat[i, 7] == "R2":
          df_actual.iat[i, 1] = cod2

       elif df_actual.iat[i, 7] == "R3":
          df_actual.iat[i, 1] = cod3

producto: Consola de videojuegos

## REVISAR ESTO DE ABAJO PORQUE rango ya esta puesto

In [ ]:
# @title
# Filtra,ps df_pp_ventas2 para mostrar solamente las filas xxxxx
# (con sufijos de rango)
tolook = prod_actual #+ '-R'
#print(tolook)
cuadro_decor_recs = df_pp_ventas2[df_pp_ventas2['producto'].str.contains( tolook)]

# Mostrar los registros filtrados
display(cuadro_decor_recs.head(50))

In [ ]:
df_actual.head(5)

## Visualizamos algunos registros

In [ ]:
'''
# To view the row with index label 28 using .loc
# This assumes your index labels are integers like in the head() output
display(df_pp_ventas2.loc[28])

# To view the row at the integer position 28 (which would be the 29th row) using .iloc
display(df_pp_ventas2.iloc[28])

# You can also view multiple rows by passing a list of index values or positions
# View rows with index labels 10, 50, and 100
display(df_pp_ventas2.loc[[10, 50, 100]])

# View rows at integer positions 10, 50, and 100
display(df_pp_ventas2.iloc[[10, 50, 100]])

# View a range of rows using slicing (iloc for integer position slicing)
display(df_pp_ventas2.iloc[20:25]) # Rows from integer position 20 up to (but not including) 25
'''

.

# ACTUALIZAMOS df_pp_ventas

In [314]:
# Tomar con pinzas ..
# Update df_pp_ventas with the modified rows from df_actual

print(f"Actualizando pp_ventas2 con 'df_{prod_actual}")

# df_ventas2 NO CONTIENE precio_rango ??? => que hago ?
df_pp_ventas2.update( df_actual[['id_producto', 'rango', 'precio_rango']] )

Actualizando pp_ventas2 con 'df_Consola de videojuegos

In [320]:

# Display the updated df_pp_ventas

#df_pp_ventas2[df_pp_ventas2['producto'].str.contains( prod_actual)].head(100)
df_pp_ventas2[df_pp_ventas2['producto'] == prod_actual].head(100)

,id_venta,id_producto,producto,precio_unit,cantidad,fecha_venta,categoria,rango,precio_rango
32,2180,173,Consola de videojuegos,102.57,9,2024-01-06,Electrónica,R3,90-126
48,2920,171,Consola de videojuegos,29.49,2,2024-01-07,Electrónica,R1,29-55
92,2980,173,Consola de videojuegos,110.60,12,2024-01-12,Electrónica,R3,90-126
117,2590,173,Consola de videojuegos,99.14,6,2024-01-15,Electrónica,R3,90-126
129,2220,171,Consola de videojuegos,31.57,1,2024-01-16,Electrónica,R1,29-55
178,2560,172,Consola de videojuegos,87.23,5,2024-01-21,Electrónica,R2,55-90
190,2690,173,Consola de videojuegos,102.40,2,2024-01-23,Electrónica,R3,90-126
208,2340,173,Consola de videojuegos,109.68,5,2024-01-25,Electrónica,R3,90-126
241,2240,171,Consola de videojuegos,43.35,8,2024-01-29,Electrónica,R1,29-55
244,2870,172,Consola de videojuegos,72.39,1,2024-01-29,Electrónica,R2,55-90
275,2680,172,Consola de videojuegos,89.96,2,2024-02-01,Electrónica,R2,55-90
362,2440,173,Consola de videojuegos,110.79,8,2024-02-11,Electrónica,R3,90-126
431,2900,172,Consola de videojuegos,63.26,2,2024-02-20,Electrónica,R2,55-90
494,2810,171,Consola de videojuegos,31.09,1,2024-02-27,Electrónica,R1,29-55
505,2110,172,Consola de videojuegos,81.69,4,2024-02-28,Electrónica,R2,55-90
562,2270,173,Consola de videojuegos,117.47,8,2024-03-07,Electrónica,R3,90-126
563,2550,173,Consola de videojuegos,118.87,6,2024-03-07,Electrónica,R3,90-126
642,2170,173,Consola de videojuegos,122.40,1,2024-03-15,Electrónica,R3,90-126
646,2950,171,Consola de videojuegos,29.14,10,2024-03-15,Electrónica,R1,29-55
654,2030,173,Consola de videojuegos,108.00,9,2024-03-16,Electrónica,R3,90-126
695,2530,171,Consola de videojuegos,54.04,8,2024-03-20,Electrónica,R1,29-55
702,2200,171,Consola de videojuegos,44.36,10,2024-03-21,Electrónica,R1,29-55
703,2650,171,Consola de videojuegos,50.77,10,2024-03-21,Electrónica,R1,29-55
713,2100,173,Consola de videojuegos,94.73,1,2024-03-22,Electrónica,R3,90-126
727,2420,172,Consola de videojuegos,72.78,9,2024-03-24,Electrónica,R2,55-90
729,2480,173,Consola de videojuegos,96.21,11,2024-03-24,Electrónica,R3,90-126
757,2830,173,Consola de videojuegos,123.72,3,2024-03-28,Electrónica,R3,90-126
784,2310,173,Consola de videojuegos,102.41,5,2024-04-01,Electrónica,R3,90-126
833,2080,173,Consola de videojuegos,100.69,7,2024-04-06,Electrónica,R3,90-126
877,2370,171,Consola de videojuegos,46.08,7,2024-04-11,Electrónica,R1,29-55
893,2490,173,Consola de videojuegos,122.79,6,2024-04-13,Electrónica,R3,90-126
928,2610,171,Consola de videojuegos,49.74,9,2024-04-16,Electrónica,R1,29-55
1014,2580,173,Consola de videojuegos,107.55,7,2024-04-26,Electrónica,R3,90-126
1075,2510,172,Consola de videojuegos,70.04,12,2024-05-02,Electrónica,R2,55-90
1114,2780,172,Consola de videojuegos,65.35,6,2024-05-06,Electrónica,R2,55-90
1139,2840,172,Consola de videojuegos,69.43,3,2024-05-09,Electrónica,R2,55-90
1161,2860,173,Consola de videojuegos,100.61,6,2024-05-12,Electrónica,R3,90-126
1210,2999,171,Consola de videojuegos,52.08,4,2024-05-17,Electrónica,R1,29-55
1247,2150,172,Consola de videojuegos,66.93,5,2024-05-21,Electrónica,R2,55-90
1379,2040,171,Consola de videojuegos,43.95,11,2024-06-06,Electrónica,R1,29-55
1386,2750,171,Consola de videojuegos,38.97,9,2024-06-07,Electrónica,R1,29-55
1433,2740,172,Consola de videojuegos,88.36,5,2024-06-13,Electrónica,R2,55-90
1469,2120,173,Consola de videojuegos,99.63,6,2024-06-19,Electrónica,R3,90-126
1480,2290,173,Consola de videojuegos,115.96,7,2024-06-21,Electrónica,R3,90-126
1518,2700,171,Consola de videojuegos,39.68,12,2024-06-26,Electrónica,R1,29-55
1530,2730,172,Consola de videojuegos,87.79,2,2024-06-28,Electrónica,R2,55-90
1575,2770,172,Consola de videojuegos,60.92,8,2024-07-03,Electrónica,R2,55-90
1606,2910,173,Consola de videojuegos,122.48,7,2024-07-07,Electrónica,R3,90-126
1675,2280,173,Consola de videojuegos,108.67,3,2024-07-16,Electrónica,R3,90-126
1683,2570,173,Consola de videojuegos,122.81,6,2024-07-17,Electrónica,R3,90-126
1695,2350,173,Consola de videojuegos,90.18,4,2024-07-19,Electrónica,R3,90-126
1737,2070,171,Consola de videojuegos,39.85,6,2024-07-24,Electrónica,R1,29-55
1751,2390,173,Consola de videojuegos,108.30,4,2024-07-26,Electrónica,R3,90-126
1791,2130,171,Consola de videojuegos,41.12,6,2024-07-31,Electrónica,R1,29-55
1802,2050,172,Consola de videojuegos,88.73,12,2024-08-01,Electrónica,R2,55-90
1815,2880,172,Consola de videojuegos,79.76,12,2024-08-02,Electrónica,R2,55-90
1838,2620,171,Consola de videojuegos,51.74,7,2024-08-04,Electrónica,R1,29-55
1840,2800,173,Consola de videojuegos,121.62,2,2024-08-04,Electrónica,R3,90-126
1846,2790,172,Consola de videojuegos,83.70,1,2024-08-05,Electrónica,R2,55-90
1904,2260,172,Consola de videojuegos,88.37,4,2024-08-14,Electrónica,R2,55-90
1930,2540,172,Consola de videojuegos,77.43,6,2024-08-18,Electrónica,R2,55-90
1958,2160,173,Consola de videojuegos,92.56,3,2024-08-21,Electrónica,R3,90-126
2003,2300,171,Consola de videojuegos,51.18,8,2024-08-26,Electrónica,R1,29-55
2021,2460,171,Consola de videojuegos,31.43,12,2024-08-28,Electrónica,R1,29-55
2061,2630,172,Consola de videojuegos,79.88,1,2024-09-02,Electrónica,R2,55-90
2071,2760,172,Consola de videojuegos,78.13,7,2024-09-04,Electrónica,R2,55-90
2107,2360,171,Consola de videojuegos,43.59,7,2024-09-08,Electrónica,R1,29-55
2141,2720,172,Consola de videojuegos,73.08,7,2024-09-12,Electrónica,R2,55-90
2201,2330,173,Consola de videojuegos,122.43,4,2024-09-19,Electrónica,R3,90-126
2209,2430,172,Consola de videojuegos,62.77,7,2024-09-21,Electrónica,R2,55-90
2239,2500,171,Consola de videojuegos,53.64,8,2024-09-25,Electrónica,R1,29-55
2244,2400,172,Consola de videojuegos,84.09,12,2024-09-26,Electrónica,R2,55-90
2253,2190,171,Consola de videojuegos,48.86,3,2024-09-27,Electrónica,R1,29-55
2260,2820,171,Consola de videojuegos,32.49,6,2024-09-28,Electrónica,R1,29-55
2270,2450,172,Consola de videojuegos,87.91,4,2024-09-29,Electrónica,R2,55-90
2272,2600,173,Consola de videojuegos,94.57,3,2024-09-29,Electrónica,R3,90-126
2384,2470,173,Consola de videojuegos,111.81,9,2024-10-12,Electrónica,R3,90-126
2389,2710,171,Consola de videojuegos,41.81,7,2024-10-13,Electrónica,R1,29-55
2401,2960,172,Consola de videojuegos,87.02,11,2024-10-15,Electrónica,R2,55-90
2439,2940,171,Consola de videojuegos,34.04,6,2024-10-22,Electrónica,R1,29-55
2500,2660,173,Consola de videojuegos,124.46,4,2024-10-29,Electrónica,R3,90-126
2519,2890,173,Consola de videojuegos,105.99,5,2024-10-31,Electrónica,R3,90-126
2562,2250,172,Consola de videojuegos,78.68,11,2024-11-07,Electrónica,R2,55-90
2581,2850,172,Consola de videojuegos,84.81,4,2024-11-09,Electrónica,R2,55-90
2588,2010,171,Consola de videojuegos,51.13,2,2024-11-10,Electrónica,R1,29-55
2598,2060,172,Consola de videojuegos,73.40,5,2024-11-11,Electrónica,R2,55-90
2694,2410,172,Consola de videojuegos,55.53,10,2024-11-23,Electrónica,R2,55-90
2696,2670,171,Consola de videojuegos,42.62,3,2024-11-23,Electrónica,R1,29-55
2704,2970,171,Consola de videojuegos,49.88,5,2024-11-24,Electrónica,R1,29-55
2759,2640,171,Consola de videojuegos,40.84,9,2024-11-30,Electrónica,R1,29-55
2781,2140,173,Consola de videojuegos,91.09,7,2024-12-02,Electrónica,R3,90-126
2801,2090,171,Consola de videojuegos,45.15,9,2024-12-05,Electrónica,R1,29-55
2815,2210,171,Consola de videojuegos,39.67,11,2024-12-07,Electrónica,R1,29-55
2832,2020,171,Consola de videojuegos,30.73,6,2024-12-10,Electrónica,R1,29-55
2862,2380,172,Consola de videojuegos,68.20,2,2024-12-14,Electrónica,R2,55-90
2877,2520,173,Consola de videojuegos,99.63,10,2024-12-15,Electrónica,R3,90-126
2916,2230,172,Consola de videojuegos,74.41,10,2024-12-20,Electrónica,R2,55-90
2922,2320,172,Consola de videojuegos,83.94,8,2024-12-21,Electrónica,R2,55-90
2997,2930,172,Consola de videojuegos,55.47,6,2024-12-30,Electrónica,R2,55-90

In [315]:
df_producto[df_producto["prod_gener"] == prod_actual].head()

,id_producto,producto,id_categoria,categoria,rango,media_rango,precio_rango,prod_gener
21,171,Consola de videojuegos-R1,3,Electrónica,R1,42.32,29-55,Consola de videojuegos
22,172,Consola de videojuegos-R2,3,Electrónica,R2,76.41,55-90,Consola de videojuegos
23,173,Consola de videojuegos-R3,3,Electrónica,R3,108.32,90-126,Consola de videojuegos

In [316]:
df_actual[df_actual["id_producto"] == 0]

Empty DataFrame
Columns: [id_venta, id_producto, producto, precio_unit, cantidad, fecha_venta, categoria, rango, precio_rango]
Index: []

In [319]:
df_actual.info()

<class 'pandas.core.frame.DataFrame'>
Index: 99 entries, 32 to 2997
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_venta      99 non-null     int64
 1   id_producto   99 non-null     int64
 2   producto      99 non-null     object
 3   precio_unit   99 non-null     float64
 4   cantidad      99 non-null     int64
 5   fecha_venta   99 non-null     object
 6   categoria     99 non-null     object
 7   rango         99 non-null     object
 8   precio_rango  99 non-null     category
dtypes: category(1), float64(1), int64(3), object(4)
memory usage: 9.2+ KB

## CONTROLAR el df_pp_ventas updated !

In [ ]:
# @title
'''
# Obtengo el index de las filas modificadas
modified_indices = df_cuadro_decor_ventas.index

# Selecciono las filas modificadas de updated df_pp_ventas2
modified_rows = df_pp_ventas2.loc[modified_indices]

# Display las filas modificadas
display(modified_rows)
'''

In [ ]:
# @title

"""
GUARDAR Y RECUPERAR EL INDEX
# Save df_pp_ventas with the index
df_pp_ventas.to_csv('df_pp_ventas_with_index.csv', index=True)

# You can then read it back with the index
df_pp_ventas_loaded = pd.read_csv('df_pp_ventas_with_index.csv', index_col=0)
display(df_pp_ventas_loaded.head())
"""

## Guardamos los dataframe en uso...

In [321]:
# Guardamos df_pp_ventas2[] junto con el indice
df_pp_ventas2.to_csv('df_pp_ventas5h.csv', index=True)

In [322]:
# Guardamos df_producto[] junto con el indice
df_producto.to_csv('df_producto5h.csv', index=True)

In [ ]:
# Guardamos df_actual
#index_col=0
#sfile = 'df_' + prod_actual + '.csv'
#print(f" guardando.. {sfile}")
#df_actual.to_csv(sfile, index=True)

 guardando.. df_Cafetera.csv

In [ ]:
# @title
'''
# Calculate the sum and count for each range using boolean indexing

rango1_data = df_adorno_pared[df_adorno_pared['precio_range'] == '25-66']
rango1_sum = rango1_data['precio_unit'].sum()
rango1_count = rango1_data.shape[0]

rango2_data = df_adorno_pared[df_adorno_pared['precio_range'] == '63-93']
rango2_sum = rango2_data['precio_unit'].sum()
rango2_count = rango2_data.shape[0]

rango3_data = df_adorno_pared[df_adorno_pared['precio_range'] == '93-120']
rango3_sum = rango3_data['precio_unit'].sum()
rango3_count = rango3_data.shape[0]


print(f"Range 25-66: Sum = {rango1_sum:.2f}, Count = {rango1_count}, Average = {(rango1_sum / rango1_count):.2f}")
print(f"Range 63-93: Sum = {rango2_sum:.2f}, Count = {rango2_count}, Average = {(rango2_sum / rango2_count):.2f}")
print(f"Range 93-120: Sum = {rango3_sum:.2f}, Count = {rango3_count}, Average = {(rango3_sum / rango3_count):.2f}")
'''

'\n# Calculate the sum and count for each range using boolean indexing\n\nrango1_data = df_adorno_pared[df_adorno_pared[\'precio_range\'] == \'25-66\']\nrango1_sum = rango1_data[\'precio_unit\'].sum()\nrango1_count = rango1_data.shape[0]\n\nrango2_data = df_adorno_pared[df_adorno_pared[\'precio_range\'] == \'63-93\']\nrango2_sum = rango2_data[\'precio_unit\'].sum()\nrango2_count = rango2_data.shape[0]\n\nrango3_data = df_adorno_pared[df_adorno_pared[\'precio_range\'] == \'93-120\']\nrango3_sum = rango3_data[\'precio_unit\'].sum()\nrango3_count = rango3_data.shape[0]\n\n\nprint(f"Range 25-66: Sum = {rango1_sum:.2f}, Count = {rango1_count}, Average = {(rango1_sum / rango1_count):.2f}")\nprint(f"Range 63-93: Sum = {rango2_sum:.2f}, Count = {rango2_count}, Average = {(rango2_sum / rango2_count):.2f}")\nprint(f"Range 93-120: Sum = {rango3_sum:.2f}, Count = {rango3_count}, Average = {(rango3_sum / rango3_count):.2f}")\n'

In [ ]:
# @title
'''
import seaborn as sns
import matplotlib.pyplot as plt

# Create a KDE plot
sns.kdeplot(df_adorno_pared["precio_unit"], fill=True)
plt.title("Kernel Density Estimate of Precio Unitario for Adorno de pared")
plt.xlabel("Precio Unitario ($)")
plt.ylabel("Density")
plt.show()
'''

'\nimport seaborn as sns\nimport matplotlib.pyplot as plt\n\n# Create a KDE plot\nsns.kdeplot(df_adorno_pared["precio_unit"], fill=True)\nplt.title("Kernel Density Estimate of Precio Unitario for Adorno de pared")\nplt.xlabel("Precio Unitario ($)")\nplt.ylabel("Density")\nplt.show()\n'

In [ ]:
df_marketing.info()
df_marketing.head()

NameError: name 'df_marketing' is not defined

In [ ]:
df_marketing2 = df_marketing.sort_values(by="producto", ascending=True)
df_marketing2.info()
# df_canales = df_marketing.copy()
# df_canales.head()
df_marketing2.head(3)

In [ ]:
df_marketing2.to_csv('df_marketing2.csv', index=False)

In [ ]:
df_ventas_final.head()

In [ ]:
'''
# Creamos DF con nombres productos unicos y sus categorias de df_ventas_final
df_producto = df_ventas_final[["producto", "categoria"]].drop_duplicates().reset_index(drop=True)

# Renombramos las columnas
df_producto.rename(columns={"producto": "prod_name", "categoria": "cat_name"}, inplace=True)

# ordenamos DF alfabeticamente por 'prod_name' en forma ascendente
df_producto = df_producto.sort_values(by="prod_name", ascending=True).reset_index(drop=True)

# Agregamos una column con los valores indices, ya ordenado producto
df_producto["prod_id"] = df_producto.index

# Crear una categoria'cat_id' numerica por cada categoria
df_producto["cat_id"] = df_producto["cat_name"].astype('category').cat.codes + 1

# Reordenamos columnas
df_producto = df_producto[["prod_id", "prod_name", "cat_id", "cat_name"]]

# Display the new DataFrame
display(df_producto.info())
'''

In [ ]:
# Display the new DataFrame
display(df_producto.head(3))

In [ ]:
#df_ventas_final.to_csv('df_ventas_final.csv', index=False)
df_producto.to_csv('df_producto.csv', index=False)

In [ ]:
df_ventas_final.head()

In [ ]:
# @title
'''
# Merge df_ventas_final with df_producto to add the 'prod_id' column
df_ventas_final2 = pd.merge(df_ventas_final, df_producto[['prod_id', 'prod_name']], left_on='producto', right_on='prod_name', how='left')

# Drop the redundant 'prod_name' column from the merge
df_ventas_final2.drop('prod_name', axis=1, inplace=True)

# Display the updated DataFrame
display(df_ventas_final2.head())
'''

In [ ]:
# Agregar a df_ventas_final la columnas "prod_id" y cat_id
df_ventas_final = pd.merge(df_ventas_final, df_producto[['prod_id', 'prod_name', 'cat_id', 'cat_name']], left_on='producto', right_on='prod_name', how='left')

# Drop the redundant 'prod_name' and 'cat_name' columns from the merge
df_ventas_final.drop(['prod_name', 'cat_name'], axis=1, inplace=True)

# Display the updated DataFrame
display(df_ventas_final.head())

In [ ]:
df_ventas_final = df_ventas_final[[ "id_venta",	"prod_id", "producto","precio_unit", "cantidad",
                                   "fecha_venta", "cat_id","categoria", "valor_venta"]]
df_ventas_final.head()

In [ ]:
df_ventas_final.to_csv('df_ventas_final4.csv', index=False)

In [ ]:
'''
# Drop the 'Unnamed: 0' column
if 'Unnamed: 0' in df_pp_ventas2.columns:
    df_pp_ventas2 = df_pp_ventas2.drop('Unnamed: 0', axis=1)

'''